[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymeta"
version = "0.1.0"
description = "A comprehensive meta-analysis package with HKSJ variance adjustment and advanced diagnostics"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "PyMeta Contributors", email = "pymeta@example.com"}
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20.0",
    "scipy>=1.7.0",
    "pandas>=1.3.0",
    "matplotlib>=3.5.0",
    "click>=8.0.0",
    "streamlit>=1.20.0",
    "dataclasses-json>=0.5.7",
]

[project.optional-dependencies]
scheduler = ["APScheduler>=3.9.0"]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "isort>=5.10.0",
    "flake8>=5.0.0",
    "mypy>=0.991",
]

[project.scripts]
pymeta = "pymeta.cli:main"

[project.urls]
Homepage = "https://github.com/mahmood789/Andypymeta"
Repository = "https://github.com/mahmood789/Andypymeta"
Issues = "https://github.com/mahmood789/Andypymeta/issues"

[tool.setuptools.packages.find]
include = ["pymeta*"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=pymeta --cov-report=term-missing"